export * from "./user.interface";
export * from "./otp.interface";
export * from "./email.interface";
export * from "./collection.interface"
export * from "./vtpass.interface"
export * from "./setting.interface"
export * from "./transaction.interface"
export * from "./card.interface"
export * from "./cable.interface"
export * from "./reloadly.interface"
export * from "./eversend.interface"
export * from "./gloesim.interface"
export * from "./super-query.interface"
export * from "./dojah.interface"
export * from "./safehaven.interface"