export const nationalityCode = {
  Afghan: "AF",
  Albanian: "AL",
  Algerian: "DZ",
  American: "US",
  Andorran: "AD",
  Angolan: "AO",
  Argentine: "AR",
  Armenian: "AM",
  Australian: "AU",
  Austrian: "AT",
  Azerbaijani: "AZ",
  Bahamian: "BS",
  Bahraini: "BH",
  Bangladeshi: "BD",
  Barbadian: "BB",
  Belarusian: "BY",
  Belgian: "BE",
  Belizean: "BZ",
  Beninese: "BJ",
  Bhutanese: "BT",
  Bolivian: "BO",
  Bosnian: "BA",
  Botswanan: "BW",
  Brazilian: "BR",
  British: "GB",
  Bruneian: "BN",
  Bulgarian: "BG",
  Burkinabe: "BF",
  Burundian: "BI",
  Cambodian: "KH",
  Cameroonian: "CM",
  Canadian: "CA",
  "Cape Verdean": "CV",
  "Central African": "CF",
  Chadian: "TD",
  Chilean: "CL",
  Chinese: "CN",
  Colombian: "CO",
  Comorian: "KM",
  Congolese: "CG",
  "Costa Rican": "CR",
  Croatian: "HR",
  Cuban: "CU",
  Cypriot: "CY",
  Czech: "CZ",
  Danish: "DK",
  Djiboutian: "DJ",
  Dominican: "DO",
  Dutch: "NL",
  "East Timorese": "TL",
  Ecuadorian: "EC",
  Egyptian: "EG",
  Emirati: "AE",
  "Equatorial Guinean": "GQ",
  Eritrean: "ER",
  Estonian: "EE",
  Ethiopian: "ET",
  Fijian: "FJ",
  Finnish: "FI",
  French: "FR",
  Gabonese: "GA",
  Gambian: "GM",
  Georgian: "GE",
  German: "DE",
  Ghanaian: "GH",
  Greek: "GR",
  Grenadian: "GD",
  Guatemalan: "GT",
  Guinean: "GN",
  Guyanese: "GY",
  Haitian: "HT",
  Honduran: "HN",
  Hungarian: "HU",
  Icelandic: "IS",
  Indian: "IN",
  Indonesian: "ID",
  Iranian: "IR",
  Iraqi: "IQ",
  Irish: "IE",
  Israeli: "IL",
  Italian: "IT",
  Ivorian: "CI",
  Jamaican: "JM",
  Japanese: "JP",
  Jordanian: "JO",
  Kazakh: "KZ",
  Kenyan: "KE",
  Kiribati: "KI",
  Kuwaiti: "KW",
  Kyrgyz: "KG",
  Laotian: "LA",
  Latvian: "LV",
  Lebanese: "LB",
  Liberian: "LR",
  Libyan: "LY",
  Liechtensteiner: "LI",
  Lithuanian: "LT",
  Luxembourgish: "LU",
  Macedonian: "MK",
  Malagasy: "MG",
  Malawian: "MW",
  Malaysian: "MY",
  Maldivian: "MV",
  Malian: "ML",
  Maltese: "MT",
  Marshallese: "MH",
  Mauritanian: "MR",
  Mauritian: "MU",
  Mexican: "MX",
  Micronesian: "FM",
  Moldovan: "MD",
  Monacan: "MC",
  Mongolian: "MN",
  Montenegrin: "ME",
  Moroccan: "MA",
  Mozambican: "MZ",
  Namibian: "NA",
  Nauruan: "NR",
  Nepalese: "NP",
  "New Zealander": "NZ",
  Nicaraguan: "NI",
  Nigerien: "NE",
  Nigerian: "NG",
  "North Korean": "KP",
  Norwegian: "NO",
  Omani: "OM",
  Pakistani: "PK",
  Palauan: "PW",
  Panamanian: "PA",
  "Papua New Guinean": "PG",
  Paraguayan: "PY",
  Peruvian: "PE",
  Philippine: "PH",
  Polish: "PL",
  Portuguese: "PT",
  Qatari: "QA",
  Romanian: "RO",
  Russian: "RU",
  Rwandan: "RW",
  "Saint Lucian": "LC",
  Salvadoran: "SV",
  Samoan: "WS",
  "San Marinese": "SM",
  "Sao Tomean": "ST",
  "Saudi Arabian": "SA",
  Senegalese: "SN",
  Serbian: "RS",
  Seychellois: "SC",
  "Sierra Leonean": "SL",
  Singaporean: "SG",
  Slovak: "SK",
  Slovenian: "SI",
  "Solomon Islander": "SB",
  Somali: "SO",
  "South African": "ZA",
  "South Korean": "KR",
  Spanish: "ES",
  "Sri Lankan": "LK",
  Sudanese: "SD",
  Surinamese: "SR",
  Swazi: "SZ",
  Swedish: "SE",
  Swiss: "CH",
  Syrian: "SY",
  Taiwanese: "TW",
  Tajik: "TJ",
  Tanzanian: "TZ",
  Thai: "TH",
  Togolese: "TG",
  Tongan: "TO",
  "Trinidadian/Tobagonian": "TT",
  Tunisian: "TN",
  Turkish: "TR",
  Turkmen: "TM",
  Tuvaluan: "TV",
  Ugandan: "UG",
  Ukrainian: "UA",
  Uruguayan: "UY",
  Uzbek: "UZ",
  Vanuatuan: "VU",
  Venezuelan: "VE",
  Vietnamese: "VN",
  Yemeni: "YE",
  Zambian: "ZM",
  Zimbabwean: "ZW",
};

export const countryIsoCode = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  "American Samoa": "AS",
  Andorra: "AD",
  Angola: "AO",
  Anguilla: "AI",
  Antarctica: "AQ",
  "Antigua and Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  Brazil: "BR",
  "British Indian Ocean Territory": "IO",
  Brunei: "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  "Christmas Island": "CX",
  "Cocos (Keeling) Islands": "CC",
  Colombia: "CO",
  Comoros: "KM",
  Congo: "CG",
  "Congo (Democratic Republic)": "CD",
  "Cook Islands": "CK",
  "Costa Rica": "CR",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Estonia: "EE",
  Eswatini: "SZ",
  Ethiopia: "ET",
  "Falkland Islands": "FK",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernsey: "GG",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  Haiti: "HT",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  "Isle of Man": "IM",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KI",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macau: "MO",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  "Marshall Islands": "MH",
  Martinique: "MQ",
  Mauritania: "MR",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  Micronesia: "FM",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Montserrat: "MS",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  "North Korea": "KP",
  "North Macedonia": "MK",
  "Northern Mariana Islands": "MP",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  Palestine: "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  Reunion: "RE",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  "Saint Helena": "SH",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Martin": "MF",
  "Saint Vincent and the Grenadines": "VC",
  Samoa: "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  "Solomon Islands": "SB",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Suriname: "SR",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  Taiwan: "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  Togo: "TG",
  Tonga: "TO",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  Tuvalu: "TV",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  "Vatican City": "VA",
  Venezuela: "VE",
  Vietnam: "VN",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};
